---
apiVersion: v1
kind: Service
metadata:
  name: {{ ServiceName }}
  namespace: {{ NamespaceName }}
spec:
  type: NodePort
  selector:
    app: {{ ServiceName }}
  ports:
    - name: http
      port: {{ ServicePort }}
      targetPort: {{ ContainerPort }}
