---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ ServiceName }}-ingress
  namespace: {{ NamespaceName }}
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
    - host: {{ DomainName }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ ServiceName }}
                port:
                  number: {{ ServicePort }}
